# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

# Deficiones de variables 

$mainMod = SUPER
$terminal = kitty
$fileManager = ranger
$menu = rofi -show run
$inter = impala
$bluet = bluetui

# Apps de inicio
exec-once = awww-daemon
exec-once = waybar
exec-once = nm-applet --indicator

# Aperturas de Apps y ventanas

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
#bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $terminal -e $fileManager
bind = $mainMod, V, togglefloating,
#bind = $mainMod, R, exec, $menu
bind = $mainMod, I, exec, $terminal -e $inter
bind = $mainMod, B, exec, $terminal -e $bluet
bind = $mainMod, W, exec, ~/.config/rofi/scripts/wallpaper.sh
bindr = $mainMod, Super_L, exec, killall rofi || rofi -show drun -show-icons -icon-theme "Papirus" -theme-str 



#Monitor Resoluccion
monitor = , highres, auto, 1
bindl =,switch:on:Lid Switch,exec,~/.config/hypr/scripts/lid.sh close  
bindl =,switch:off:Lid Switch,exec,~/.config/hypr/scripts/lid.sh open

# Navegacion entre ventanas

bind = $mainMod, Left, movefocus, l
bind = $mainMod, Right, movefocus, r
bind = $mainMod, Up, movefocus, u
bind = $mainMod, Down ,movefocus, d 
bind = $mainMod, grave, togglespecialworkspace, magic
bind = $mainMod CTRL SHIFT, grave, movetoworkspace, special:magic
bind = $mainMod SHIFT, grave, movetoworkspace, 1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Botones multimedia para el portatil 
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2.5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2.5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-



